/*
*   *********************************************************************************************************************
*  	TITLE:              Implants and Supplies 
*  	AUTHOR:             
*   PROJECT:            STSTVT- Quality Registry 
*  	DESCRIPTION:        Get details on the Implants for the Patient
*	  DATABASE:	          Clarity		
*  	VERSION CONTROL:	
*   -----------------        ----------------------------------          ------------------------------------------------ 
		DATE             			    Modified By                          	       	    Changes
	-----------------        ----------------------------------          ------------------------------------------------      													
*
*
*   *********************************************************************************************************************
*   Restricting  Elements:
	-----------------        ----------------------------------          ------------------------------------------------ 
		Table Name				    Column Name									    DESCRIPTION
	-----------------        ----------------------------------          ------------------------------------------------
*       OR_IMP				        IMPLANT_ID 							    filtering based on Implant internal id
*   *********************************************************************************************************************
*	Table Used:
	--------------------------------------------------------------------------------------------------------------------- 
 
*   *********************************************************************************************************************
*/


WITH MAIN AS (
  /*+ MATERIALIZE */
  SELECT
    PAT.PAT_ID,
    PAT.PAT_MRN_ID,
    ORC.SURGERY_DATE,
    ORC.OR_CASE_ID,
    ORL.LOG_ID,
    ORL.SERVICE_C,                    -- pushed here so IMP doesn't re-join OR_LOG
    SA.SERV_AREA_NAME,
    LOC.LOC_NAME,
    PATL.OR_LINK_CSN,
    PATL.PAT_ENC_CSN_ID
  FROM OR_CASE ORC
  INNER JOIN OR_LOG ORL
    ON ORL.LOG_ID = ORC.LOG_ID
  /* removed unused LEFT JOIN OR_CASE_2 */
  LEFT OUTER JOIN PAT_OR_ADM_LINK PATL
    ON PATL.CASE_ID = ORC.OR_CASE_ID
  /* removed unused LEFT JOIN PAT_ENC */
  LEFT OUTER JOIN PATIENT PAT
    ON ORC.PAT_ID = PAT.PAT_ID
  LEFT OUTER JOIN CLARITY_LOC LOC
    ON LOC.LOC_ID = ORC.LOC_ID
  LEFT OUTER JOIN CLARITY_SA SA
    ON LOC.SERV_AREA_ID = SA.SERV_AREA_ID
  WHERE ORC.SURGERY_DATE BETWEEN TRUNC(SYSDATE) - 365 AND TRUNC(SYSDATE)
    AND ORL.LOG_TYPE_C = 0
),
SUP AS (
  SELECT
    M.SERV_AREA_NAME AS "SERVICEAREA",
    M.LOC_NAME AS "LOCATION",
    M.OR_LINK_CSN AS "ENCOUNTERID",
    M.SURGERY_DATE,
    M.PAT_MRN_ID AS "MRN",
    M.OR_CASE_ID AS "CASEID",
    M.LOG_ID AS "LOGID",
    '' AS IMPLANT_ID,
    'SUPPLY' AS "ITEMCLASS",
    PCKSUP.SUPPLY_ID AS "ITEMID",
    SUP.SUPPLY_NAME AS "ITEMNAME",
    ITEMTYPE.NAME AS "ITEMTYPE",
    ZPT.NAME AS "PERIOPERATIVELOCATION",
    PRO.OR_PROC_ID AS "PROCEDURECODE",
    OPR.PROC_NAME AS "PROCEDURE",
    ZMFC.NAME AS "MANUFACTURER",
    MFC.MAN_CTLG_NUM AS "MANUFACTURER#",
    '' AS "LOTNUMBER",
    '' AS "SERIAL#",
    '' AS "MODELNUMBER",
    '' AS "IMPLANTAREA",
    '' AS "IMPLANTEDDATE",
    '' AS "EXPLANTEDDATE",
    '' AS "WASTED_DATE",
    NULL AS "EXPIRATIONDATE",
    PCKSUP.NUM_NEEDED_OPEN AS "QUANTITYOPEN",
    PCKSUP.NUM_SUPPLIES_PRN AS "QUANTITYPRN",
    PCKSUP.NUM_NEEDED_OPEN AS "QUANTITY",
    PCKSUP.SUPPLIES_USED AS "QUANTITYUSED",
    PCKSUP.SUPPLIES_WASTED AS "QUANTITYWASTED",
    RSNWASTED.NAME AS "REASONWASTED",
    PCKSUP.RSN_SUP_WASTED_C AS "REASONWASTEDCODE",
    NVL(PCKSUP.SUP_UNIT_COST, 0) AS "COSTPERUNIT",
    PCKSUP.CHARGEABLE_YN AS "CHARGEABLE?",
    NVL(PCKSUP.SUP_UNIT_CHARGE, 0) AS "CHARGEPERUNIT",
    NVL(PCKSUP.SUP_UNIT_WASTE_CHRG, 0) AS "WASTEDCHARGEPERUNIT",
    INVLOC.LOC_NAME AS "INVENTORYLOCATION",
    '' AS "PRODUCT_STATUS",
    '' AS "SERVICE"
  FROM MAIN M
  LEFT OUTER JOIN OR_PKLST PCK
    ON PCK.LOG_ID = M.LOG_ID
  LEFT OUTER JOIN OR_CASE_ALL_PROC PRO
    ON M.OR_CASE_ID = PRO.OR_CASE_ID
  LEFT OUTER JOIN OR_PROC OPR
    ON OPR.OR_PROC_ID = PRO.OR_PROC_ID
  LEFT OUTER JOIN OR_PKLST_SUP_LIST PCKSUP
    ON PCKSUP.PICK_LIST_ID = PCK.PICK_LIST_ID
   AND (PCKSUP.IMPLANT_YN IS NULL OR PCKSUP.IMPLANT_YN = 'N')
  LEFT OUTER JOIN OR_SPLY SUP
    ON PCKSUP.SUPPLY_ID = SUP.SUPPLY_ID
  LEFT OUTER JOIN ZC_OR_TYPE_OF_ITEM ITEMTYPE
    ON SUP.TYPE_OF_ITEM_C = ITEMTYPE.TYPE_OF_ITEM_C
  LEFT OUTER JOIN ZC_OR_RSN_WASTED RSNWASTED
    ON PCKSUP.RSN_SUP_WASTED_C = RSNWASTED.RSN_SUP_WASTED_C
  LEFT OUTER JOIN CLARITY_LOC INVLOC
    ON PCKSUP.SUPPLY_INV_LOC_ID = INVLOC.LOC_ID
  LEFT OUTER JOIN OR_SPLY_MANFACTR MFC
    ON SUP.SUPPLY_ID = MFC.ITEM_ID AND MFC.LINE = 1
  LEFT OUTER JOIN ZC_OR_MANUFACTURER ZMFC
    ON MFC.MANUFACTURER_C = ZMFC.MANUFACTURER_C
  LEFT OUTER JOIN ZC_PICKLIST_TYPE ZPT
    ON ZPT.PICKLIST_TYPE_C = PCK.PICK_LIST_TYPE_C
),
IMP AS (
  SELECT
    M.SERV_AREA_NAME AS "SERVICEAREA",
    M.LOC_NAME AS "LOCATION",
    M.OR_LINK_CSN AS "ENCOUNTERID",
    M.SURGERY_DATE,
    M.PAT_MRN_ID AS "MRN",
    M.OR_CASE_ID AS "CASEID",
    M.LOG_ID AS "LOGID",
    LNLG.IMPLANT_ID,
    'IMPLANT' AS "ITEMCLASS",
    LNLG.IMPLANT_ID AS "ITEMID",
    IMP.IMPLANT_NAME AS "ITEMNAME",
    IMPTYPE.NAME AS "ITEMTYPE",
    ZPT.NAME AS "PERIOPERATIVELOCATION",
    TO_CHAR(CHG.PROCEDURE_CODE_ID) AS "PROCEDURECODE",
    EAP.PROC_NAME AS "PROCEDURE",
    ZMFC.NAME AS "MANUFACTURER",
    IMP.MANUF_NUM AS "MANUFACTURER#",
    IMP.LOT_NUMBER AS "LOTNUMBER",
    IMP.SERIAL_NUMBER AS "SERIAL#",
    IMP.MODEL_NUMBER AS "MODELNUMBER",
    ZAREA.NAME AS "IMPLANTAREA",
    OR_IMP_IMPLANT.IMPLANTED_DATE AS "IMPLANTEDDATE",
    OR_IMP_EXPLANT.EXPLANTED_DATE AS "EXPLANTEDDATE",
    OR_IMP_WASTED.WASTED_DATE,
    IMP.EXPIRATION_DATE AS "EXPIRATIONDATE",
    NULL AS "QUANTITYOPEN",
    NULL AS "QUANTITYPRN",
    CHG.QUANTITY AS "QUANTITY",
    CASE
      WHEN LNLG.IMPLANT_USAGE_C IS NULL OR LNLG.IMPLANT_USAGE_C = 1 THEN LNLG.IMPLANT_NUM_USED
      ELSE 0
    END AS "QUANTITYUSED",
    CASE
      WHEN LNLG.IMPLANT_USAGE_C = 2 THEN LNLG.IMPLANT_NUM_USED
      ELSE 0
    END AS "QUANTITYWASTED",
    WASTE.NAME AS "REASONWASTED",
    LNLG.IMPLANT_RSN_WSTD_C AS "REASONWASTEDCODE",
    NVL(IMP.COST_PER_UNIT, 0) AS "COSTPERUNIT",
    IMP.CHARGEABLE_YN AS "CHARGEABLE?",
    CASE
      WHEN (LNLG.IMPLANT_ACTION_C <> 3 AND LNLG.IMPLANT_UNIT_CHARGE IS NOT NULL)
      THEN LNLG.IMPLANT_UNIT_CHARGE
      ELSE 0
    END AS "CHARGEPERUNIT",
    CASE
      WHEN (LNLG.IMPLANT_ACTION_C = 3 AND LNLG.IMPLANT_UNIT_CHARGE IS NOT NULL)
      THEN LNLG.IMPLANT_UNIT_CHARGE
      ELSE 0
    END AS "WASTEDCHARGEPERUNIT",
    INVLOC.LOC_NAME AS "INVENTORYLOCATION",
    ZC_OR_IMP_STATUS.NAME AS "PRODUCT_STATUS",
    ZC_OR_SERVICE.NAME AS "SERVICE"
  FROM MAIN M
  INNER JOIN OR_LOG_LN_IMPLANT ORLN
    ON M.LOG_ID = ORLN.LOG_ID
  LEFT OUTER JOIN OR_LNLG_IMPLANTS LNLG
    ON ORLN.IMPLANTS_ID = LNLG.RECORD_ID
  LEFT OUTER JOIN OR_IMP IMP
    ON LNLG.IMPLANT_ID = IMP.IMPLANT_ID
  /* keep original semantics for these joins; only replaced OR_CASE.LOG_ID with M.LOG_ID */
  LEFT OUTER JOIN OR_IMP_IMPLANT
    ON OR_IMP_IMPLANT.IMPLANT_LOG_ID = M.LOG_ID
  LEFT OUTER JOIN OR_IMP_EXPLANT
    ON OR_IMP_IMPLANT.IMPLANT_ID = OR_IMP_EXPLANT.IMPLANT_ID
  LEFT OUTER JOIN OR_IMP_WASTED
    ON IMP.IMPLANT_ID = OR_IMP_WASTED.IMPLANT_ID
  LEFT OUTER JOIN ZC_OR_IMP_STATUS
    ON ZC_OR_IMP_STATUS.STATUS_C = IMP.STATUS_C
  LEFT OUTER JOIN ZC_OR_SERVICE
    ON ZC_OR_SERVICE.SERVICE_C = M.SERVICE_C
  LEFT OUTER JOIN OR_LOG_CHARGES CHG
    ON CHG.LOG_ID = M.LOG_ID
   AND IMP.IMPLANT_ID = CHG.CHARGE_IMPLANT_ID
  LEFT OUTER JOIN ZC_IMPLANT_AREA ZAREA
    ON ZAREA.IMPLANT_AREA_C = IMP.IMPLANT_AREA_C
  LEFT OUTER JOIN CLARITY_LOC INVLOC
    ON IMP.SITE_ID = INVLOC.LOC_ID
  LEFT OUTER JOIN ZC_OR_IMPLANT_TYPE IMPTYPE
    ON IMP.IMPLANT_TYPE_C = IMPTYPE.IMPLANT_TYPE_C
  LEFT OUTER JOIN ZC_OR_RSN_WASTE WASTE
    ON LNLG.IMPLANT_RSN_WSTD_C = WASTE.REASON_WASTED_C
  LEFT OUTER JOIN ZC_OR_MANUFACTURER ZMFC
    ON ZMFC.MANUFACTURER_C = IMP.MANUFACTURER_C
  LEFT OUTER JOIN CLARITY_EAP EAP
    ON EAP.PROC_ID = CHG.PROCEDURE_CODE_ID
  LEFT OUTER JOIN ZC_PICKLIST_TYPE ZPT
    ON ZPT.PICKLIST_TYPE_C = CHG.PICKLIST_TYPE_C
),
ITEM AS (
  SELECT * FROM SUP
  UNION ALL
  SELECT * FROM IMP
)
SELECT DISTINCT
  ENCOUNTERID,
  MRN,
  SURGERY_DATE,
  CASEID,
  LOGID,
  IMPLANT_ID,
  ITEMCLASS,
  ITEMID,
  ITEMNAME,
  ITEMTYPE,
  PERIOPERATIVELOCATION,
  PROCEDURECODE,
  "PROCEDURE",
  MANUFACTURER,
  "MANUFACTURER#",
  LOTNUMBER,
  "SERIAL#",
  MODELNUMBER,
  IMPLANTAREA,
  CASE
    WHEN "IMPLANTEDDATE" = TO_DATE('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN NULL
    ELSE "IMPLANTEDDATE"
  END AS "IMPLANTEDDATE",
  CASE
    WHEN "EXPLANTEDDATE" = TO_DATE('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN NULL
    ELSE "EXPLANTEDDATE"
  END AS "EXPLANTEDDATE",
  CASE
    WHEN WASTED_DATE = TO_DATE('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN NULL
    ELSE WASTED_DATE
  END AS "WASTED_DATE",
  EXPIRATIONDATE,
  QUANTITYOPEN,
  QUANTITYPRN,
  QUANTITY,
  QUANTITYUSED,
  QUANTITYWASTED,
  REASONWASTED,
  REASONWASTEDCODE,
  "COSTPERUNIT",
  "CHARGEABLE?",
  "CHARGEPERUNIT",
  "WASTEDCHARGEPERUNIT",
  INVENTORYLOCATION,
  PRODUCT_STATUS,
  SERVICE,
  SERVICEAREA,
  LOCATION
FROM ITEM;
