/*
*   *********************************************************************************************************************
*    TITLE:              Spcial History
*    AUTHOR:              
*    PROJECT:            STSTVT- Quality Registry            
*    DESCRIPTION:        Get Patient social history details
* 
* 
*  DATABASE:  Clarity (Epic)
*  VERSION CONTROL: 
*   -----------------     ----------------------------------          ------------------------------------------------
DATE                       Modified By                                 Changes
-----------------          ----------------------------------          ------------------------------------------------
*********************************************************************************************************************
*   Restricting  Elements:
-----------------        ----------------------------------          ------------------------------------------------
Table Name              Column Name                                    DESCRIPTION

-----------------        ----------------------------------          ------------------------------------------------
*   *********************************************************************************************************************
*  Table Used:
---------------------------------------------------------------------------------------------------------------------
SOCIAL_HX, ZC_HISTORY_SOURCE, PAT_SOCIAL_HX_DOC
*   *********************************************************************************************************************
*/

/*
*   *********************************************************************************************************************
*    TITLE:              Spcial History
*    AUTHOR:              
*    PROJECT:            STSTVT- Quality Registry            
*    DESCRIPTION:        Get Patient social history details
* 
* 
*  DATABASE:  Clarity (Epic)
*  VERSION CONTROL: 
*   -----------------     ----------------------------------          ------------------------------------------------
DATE                       Modified By                                 Changes
-----------------          ----------------------------------          ------------------------------------------------
*********************************************************************************************************************
*   Restricting  Elements:
-----------------        ----------------------------------          ------------------------------------------------
Table Name              Column Name                                    DESCRIPTION

-----------------        ----------------------------------          ------------------------------------------------
*   *********************************************************************************************************************
*  Table Used:
---------------------------------------------------------------------------------------------------------------------
SOCIAL_HX, ZC_HISTORY_SOURCE, PAT_SOCIAL_HX_DOC
*   *********************************************************************************************************************
*/

WITH params AS ( -- single-row driving parameters
    SELECT
        TRUNC(ADD_MONTHS(SYSDATE, -24), 'MM') AS period_start, -- start of month two years ago (month start)
        TRUNC(SYSDATE, 'MM')                   AS period_end,   -- start of current month
        SYSDATE - 2                            AS recent_cutoff -- not used
    FROM DUAL
),
base_sh AS (
    SELECT
        PAT_ENC.PAT_ID,
        PAT.PAT_MRN_ID as MRN,
        CAST(s.PAT_ENC_CSN_ID            AS VARCHAR2(4000)) as PAT_ENC_CSN_ID,
        TO_CHAR( (FROM_TZ(CAST(s.CONTACT_DATE AS TIMESTAMP), 'America/New_York') AT TIME ZONE 'UTC'),
                 'YYYY-MM-DD"T"HH24:MI:SS"Z"')                                   AS InputDate,
        CAST(s.ABSTINENCE_YN            AS VARCHAR2(4000)) as ABSTINENCE_YN,
        CAST(s.CIGARETTES_YN            AS VARCHAR2(4000)) as CIGARETTES_YN,
        CAST(s.SMOKING_QUIT_DATE        AS VARCHAR2(4000)) as SMOKING_QUIT_DATE,
        CAST(s.IS_ALCOHOL_USER          AS VARCHAR2(4000)) as IS_ALCOHOL_USER,
        CAST(s.IS_ILL_DRUG_USER         AS VARCHAR2(4000)) as IS_ILL_DRUG_USER,
        CAST(ZC_ALCOHOL_USE.NAME        AS VARCHAR2(4000)) as ALCOHOL_USE,
        CAST(ZC_ILL_DRUG_USER.NAME      AS VARCHAR2(4000)) as ILL_DRUG_USER,
        CAST(ZC_SEXUALLY_ACTIVE.NAME    AS VARCHAR2(4000)) as SEXUALLY_ACTIVE,
        CAST(ZC_TOBACCO_USER.NAME       AS VARCHAR2(4000)) as TOBACCO_USER,
        CAST(ZC_SMOKELESS_TOB_U.NAME    AS VARCHAR2(4000)) as SMOKELESS_TOB,
        CAST(ZC_SMOKING_TOB_USE.NAME    AS VARCHAR2(4000)) as SMOKING_TOB_USE,
        CAST(s.TOBACCO_PAK_PER_DY       AS VARCHAR2(4000)) as TOBACCO_PAK_PER_DY,
        CAST(s.TOBACCO_USED_YEARS       AS VARCHAR2(4000)) as TOBACCO_USED_YEARS,
        CAST(s.TOBACCO_COMMENT          AS VARCHAR2(4000)) as TOBACCO_COMMENT,
        CAST(s.PIPES_YN                 AS VARCHAR2(4000)) as PIPES_YN,
        CAST(s.CIGARS_YN                AS VARCHAR2(4000)) as CIGARS_YN,
        CAST(s.SNUFF_YN                 AS VARCHAR2(4000)) as SNUFF_YN,
        CAST(s.CHEW_YN                  AS VARCHAR2(4000)) as CHEW_YN,
        CAST(s.ALCOHOL_OZ_PER_WK        AS VARCHAR2(4000)) as ALCOHOL_OZ_PER_WK,
        CAST(s.ALCOHOL_COMMENT          AS VARCHAR2(4000)) as ALCOHOL_COMMENT,
        CAST(s.IV_DRUG_USER_YN          AS VARCHAR2(4000)) as IV_DRUG_USER_YN,
        CAST(s.ILLICIT_DRUG_FREQ        AS VARCHAR2(4000)) as ILLICIT_DRUG_FREQ,
        CAST(s.ILLICIT_DRUG_CMT         AS VARCHAR2(4000)) as ILLICIT_DRUG_CMT,
        CAST(s.FEMALE_PARTNER_YN        AS VARCHAR2(4000)) as FEMALE_PARTNER_YN,
        CAST(s.MALE_PARTNER_YN          AS VARCHAR2(4000)) as MALE_PARTNER_YN,
        CAST(s.CONDOM_YN                AS VARCHAR2(4000)) as CONDOM_YN,
        CAST(s.PILL_YN                  AS VARCHAR2(4000)) as PILL_YN,
        CAST(s.DIAPHRAGM_YN             AS VARCHAR2(4000)) as DIAPHRAGM_YN,
        CAST(s.IUD_YN                   AS VARCHAR2(4000)) as IUD_YN,
        CAST(s.SURGICAL_YN              AS VARCHAR2(4000)) as SURGICAL_YN,
        CAST(s.SPERMICIDE_YN            AS VARCHAR2(4000)) as SPERMICIDE_YN,
        CAST(s.IMPLANT_YN               AS VARCHAR2(4000)) as IMPLANT_YN,
        CAST(s.RHYTHM_YN                AS VARCHAR2(4000)) as RHYTHM_YN,
        CAST(s.INJECTION_YN             AS VARCHAR2(4000)) as INJECTION_YN,
        CAST(s.SPONGE_YN                AS VARCHAR2(4000)) as SPONGE_YN,
        CAST(s.INSERTS_YN               AS VARCHAR2(4000)) as INSERTS_YN,
        CAST(s.SEX_COMMENT              AS VARCHAR2(4000)) as SEX_COMMENT,
        CAST(s.YEARS_EDUCATION          AS VARCHAR2(4000)) as YEARS_EDUCATION,
        CAST(ALCOHOL_SOURCE.NAME        AS VARCHAR2(4000)) as ALCOHOL_SOURCE,
        CAST(DRUG_SOURCE.NAME           AS VARCHAR2(4000)) as DRUG_SOURCE,
        CAST(SEX_SOURCE.NAME            AS VARCHAR2(4000)) as SEX_SOURCE,
        TO_CHAR(s.SMOKING_START_DATE, 'YYYY-MM-DD')                   AS SMOKING_START_DATE,
        TO_CHAR(s.SMOKELESS_QUIT_DATE, 'YYYY-MM-DD')                  AS SMOKELESS_QUIT_DATE,
        CAST(s.UNKNOWN_FAM_HX_YN        AS VARCHAR2(4000)) as UNKNOWN_FAM_HX_YN,
        CAST(SOC_PHONE_SOURCE.NAME      AS VARCHAR2(4000)) as SOC_PHONE_SOURCE,
        CAST(SOC_TOGETHER_SOURCE.NAME   AS VARCHAR2(4000)) as SOC_TOGETHER_SOURCE,
        CAST(SOC_CHURCH_SOURCE.NAME     AS VARCHAR2(4000)) as SOC_CHURCH_SOURCE,
        CAST(SOC_MEETINGS_SOURCE.NAME   AS VARCHAR2(4000)) as SOC_MEETINGS_SOURCE,
        CAST(SOC_MEMBER_SOURCE.NAME     AS VARCHAR2(4000)) as SOC_MEMBER_SOURCE,
        CAST(SOC_LIVING_SOURCE.NAME     AS VARCHAR2(4000)) as SOC_LIVING_SOURCE,
        CAST(PHYS_DPW_SOURCE.NAME       AS VARCHAR2(4000)) as PHYS_DPW_SOURCE,
        CAST(PHYS_MPS_SOURCE.NAME       AS VARCHAR2(4000)) as PHYS_MPS_SOURCE,
        CAST(STRESS_SOURCE.NAME         AS VARCHAR2(4000)) as STRESS_SOURCE,
        CAST(EDUCATION_SOURCE.NAME      AS VARCHAR2(4000)) as EDUCATION_SOURCE,
        CAST(FINANCIAL_SOURCE.NAME      AS VARCHAR2(4000)) as FINANCIAL_SOURCE,
        CAST(IPV_EMOTIONAL_ABUSE_SOURCE.NAME AS VARCHAR2(4000)) as IPV_EMOTIONAL_ABUSE_SOURCE,
        CAST(IPV_FEAR_SOURCE.NAME       AS VARCHAR2(4000)) as IPV_FEAR_SOURCE,
        CAST(IPV_SEXABUSE_SOURCE.NAME   AS VARCHAR2(4000)) as IPV_SEXABUSE_SOURCE,
        CAST(IPV_PHYSABUSE_SOURCE.NAME  AS VARCHAR2(4000)) as IPV_PHYSABUSE_SOURCE,
        CAST(ALCOHOL_FREQ_SOURCE.NAME   AS VARCHAR2(4000)) as ALCOHOL_FREQ_SOURCE, -- kept original join logic
        CAST(ALCOHOL_STD_DRINK_SOURCE.NAME AS VARCHAR2(4000)) as ALCOHOL_STD_DRINK_SOURCE,
        CAST(FOOD_WORRY_SOURCE.NAME     AS VARCHAR2(4000)) as FOOD_WORRY_SOURCE,
        CAST(FOOD_SCARCITY_SOURCE.NAME  AS VARCHAR2(4000)) as FOOD_SCARCITY_SOURCE,
        CAST(TRANS_MED_SOURCE.NAME      AS VARCHAR2(4000)) as TRANS_MED_SOURCE,
        CAST(TRANS_NONMED_SOURCE.NAME   AS VARCHAR2(4000)) as TRANS_NONMED_SOURCE,
        CAST(s.FAM_PAT_ADPT_PAR_1       AS VARCHAR2(4000)) as FAM_PAT_ADPT_PAR_1,
        CAST(s.FAM_PAT_ADPT_PAR_2       AS VARCHAR2(4000)) as FAM_PAT_ADPT_PAR_2,
        CAST(ZC_EDU_LEVEL.NAME          AS VARCHAR2(4000)) as EDU_LEVEL,
        CAST(ZC_FIN_RESOURCE_STRAIN.NAME AS VARCHAR2(4000)) as FIN_RESOURCE_STRAIN,
        CAST(ZC_IPV_EMOTIONAL_ABUSE.NAME AS VARCHAR2(4000)) as IPV_EMOTIONAL_ABUSE,
        CAST(ZC_IPV_FEAR.NAME           AS VARCHAR2(4000)) as IPV_FEAR,
        CAST(ZC_IPV_SEXUAL_ABUSE.NAME   AS VARCHAR2(4000)) as IPV_SEXUAL_ABUSE,
        CAST(ZC_IPV_PHYSICAL_ABUSE.NAME AS VARCHAR2(4000)) as IPV_PHYSICAL_ABUSE,
        CAST(ZC_ALCOHOL_FREQ.NAME       AS VARCHAR2(4000)) as ALCOHOL_FREQ,
        CAST(ZC_ALCOHOL_DRINKS_PER_DAY.NAME AS VARCHAR2(4000)) as ALCOHOL_DRINKS_PER_DAY,
        CAST(ZC_ALCOHOL_BINGE.NAME      AS VARCHAR2(4000)) as ALCOHOL_BINGE,
        CAST(ZC_LIVING_W_SPOUSE.NAME    AS VARCHAR2(4000)) as LIVING_W_SPOUSE,
        CAST(ZC_DAILY_STRESS.NAME       AS VARCHAR2(4000)) as DAILY_STRESS,
        CAST(ZC_PHONE_COMMUNICATION.NAME AS VARCHAR2(4000)) as PHONE_COMMUNICATION,
        CAST(ZC_SOCIALIZATION_FREQ.NAME AS VARCHAR2(4000)) as SOCIALIZATION_FREQ,
        CAST(ZC_CHURCH_ATTENDANCE.NAME  AS VARCHAR2(4000)) as CHURCH_ATTENDANCE,
        CAST(ZC_CLUBMTG_ATTENDANCE.NAME AS VARCHAR2(4000)) as CLUBMTG_ATTENDANCE,
        CAST(ZC_CLUB_MEMBER.NAME        AS VARCHAR2(4000)) as CLUB_MEMBER,
        CAST(ZC_PHYS_ACT_DAYS_PER_WEEK.NAME AS VARCHAR2(4000)) as PHYS_ACT_DAYS_PER_WEEK,
        CAST(ZC_PHYS_ACT_MIN_PER_SESS.NAME AS VARCHAR2(4000)) as PHYS_ACT_MIN_PER_SESS,
        CAST(ZC_FOOD_INSECURITY_SCARCE.NAME AS VARCHAR2(4000)) as FOOD_INSECURITY_SCARC,
        CAST(ZC_FOOD_INSECURITY_WORRY.NAME AS VARCHAR2(4000)) as FOOD_INSECURITY_WORRY,
        CAST(ZC_MED_TRANSPORT_NEEDS.NAME AS VARCHAR2(4000)) as MED_TRANSPORT_NEEDS,
        CAST(ZC_OTHER_TRANSPORT_NEEDS.NAME AS VARCHAR2(4000)) as OTHER_TRANSPORT_NEEDS
    FROM SOCIAL_HX s
    CROSS JOIN params p -- allows single evaluation of period_start/period_end and predicate pushdown
    INNER JOIN PAT_ENC PAT_ENC ON s.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID
    INNER JOIN PATIENT PAT     ON PAT_ENC.PAT_ID = PAT.PAT_ID
    -- Make the original left join + where predicate explicit; preserves exact filtering and row-multiplicity semantics
    INNER JOIN PATIENT_3 vp    ON vp.PAT_ID = s.PAT_ID AND vp.IS_TEST_PAT_YN = 'N'
    -- Sources (preserved as in original)
    LEFT JOIN ZC_HISTORY_SOURCE ALC_BINGE_SOURCE            ON ALC_BINGE_SOURCE.HISTORY_SOURCE_C       = s.ALC_BINGE_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE ALCOHOL_SOURCE              ON ALCOHOL_SOURCE.HISTORY_SOURCE_C         = s.ALCOHOL_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE DRUG_SOURCE                 ON DRUG_SOURCE.HISTORY_SOURCE_C            = s.DRUG_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SEX_SOURCE                  ON SEX_SOURCE.HISTORY_SOURCE_C             = s.SEX_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_PHONE_SOURCE            ON SOC_PHONE_SOURCE.HISTORY_SOURCE_C       = s.SOC_PHONE_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_TOGETHER_SOURCE         ON SOC_TOGETHER_SOURCE.HISTORY_SOURCE_C    = s.SOC_TOGETHER_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_CHURCH_SOURCE           ON SOC_CHURCH_SOURCE.HISTORY_SOURCE_C      = s.SOC_CHURCH_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_MEETINGS_SOURCE         ON SOC_MEETINGS_SOURCE.HISTORY_SOURCE_C    = s.SOC_MEETINGS_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_MEMBER_SOURCE           ON SOC_MEMBER_SOURCE.HISTORY_SOURCE_C      = s.SOC_MEMBER_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE SOC_LIVING_SOURCE           ON SOC_LIVING_SOURCE.HISTORY_SOURCE_C      = s.SOC_LIVING_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE PHYS_DPW_SOURCE             ON PHYS_DPW_SOURCE.HISTORY_SOURCE_C        = s.PHYS_DPW_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE PHYS_MPS_SOURCE             ON PHYS_MPS_SOURCE.HISTORY_SOURCE_C        = s.PHYS_MPS_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE STRESS_SOURCE               ON STRESS_SOURCE.HISTORY_SOURCE_C          = s.STRESS_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE EDUCATION_SOURCE            ON EDUCATION_SOURCE.HISTORY_SOURCE_C       = s.EDUCATION_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE FINANCIAL_SOURCE            ON FINANCIAL_SOURCE.HISTORY_SOURCE_C       = s.FINANCIAL_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE IPV_EMOTIONAL_ABUSE_SOURCE  ON IPV_EMOTIONAL_ABUSE_SOURCE.HISTORY_SOURCE_C = s.IPV_EMOTIONAL_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE IPV_FEAR_SOURCE             ON IPV_FEAR_SOURCE.HISTORY_SOURCE_C        = s.IPV_FEAR_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE IPV_SEXABUSE_SOURCE         ON IPV_SEXABUSE_SOURCE.HISTORY_SOURCE_C    = s.IPV_SEXABUSE_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE IPV_PHYSABUSE_SOURCE        ON IPV_PHYSABUSE_SOURCE.HISTORY_SOURCE_C   = s.IPV_PHYSABUSE_SRC_C
    -- Note: kept the original (likely typo) join for ALCOHOL_FREQ_SOURCE to preserve exact semantics
    LEFT JOIN ZC_HISTORY_SOURCE ALCOHOL_FREQ_SOURCE         ON SOC_LIVING_SOURCE.HISTORY_SOURCE_C      = s.SOC_LIVING_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE ALCOHOL_STD_DRINK_SOURCE    ON ALCOHOL_STD_DRINK_SOURCE.HISTORY_SOURCE_C = s.ALC_STD_DRINK_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE FOOD_WORRY_SOURCE           ON FOOD_WORRY_SOURCE.HISTORY_SOURCE_C      = s.FOOD_WORRY_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE FOOD_SCARCITY_SOURCE        ON FOOD_SCARCITY_SOURCE.HISTORY_SOURCE_C   = s.FOOD_SCARCITY_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE TRANS_MED_SOURCE            ON TRANS_MED_SOURCE.HISTORY_SOURCE_C       = s.TRANS_MED_SRC_C
    LEFT JOIN ZC_HISTORY_SOURCE TRANS_NONMED_SOURCE         ON TRANS_NONMED_SOURCE.HISTORY_SOURCE_C    = s.TRANS_NONMED_SRC_C
    -- Code/Name lookups
    LEFT JOIN ZC_SEXUALLY_ACTIVE        ON ZC_SEXUALLY_ACTIVE.SEXUALLY_ACTIVE_C              = s.SEXUALLY_ACTIVE_C
    LEFT JOIN ZC_ALCOHOL_USE            ON ZC_ALCOHOL_USE.ALCOHOL_USE_C                      = s.ALCOHOL_USE_C
    LEFT JOIN ZC_ILL_DRUG_USER          ON ZC_ILL_DRUG_USER.ILL_DRUG_USER_C                  = s.ILL_DRUG_USER_C
    LEFT JOIN ZC_TOBACCO_USER           ON ZC_TOBACCO_USER.TOBACCO_USER_C                    = s.TOBACCO_USER_C
    LEFT JOIN ZC_SMOKELESS_TOB_U        ON ZC_SMOKELESS_TOB_U.SMOKELESS_TOB_U_C              = s.SMOKELESS_TOB_USE_C
    LEFT JOIN ZC_SMOKING_TOB_USE        ON ZC_SMOKING_TOB_USE.SMOKING_TOB_USE_C              = s.SMOKING_TOB_USE_C
    LEFT JOIN ZC_EDU_LEVEL              ON ZC_EDU_LEVEL.EDU_LEVEL_C                          = s.EDU_LEVEL_C
    LEFT JOIN ZC_FIN_RESOURCE_STRAIN    ON ZC_FIN_RESOURCE_STRAIN.FIN_RESOURCE_STRAIN_C      = s.FIN_RESOURCE_STRAIN_C
    LEFT JOIN ZC_IPV_EMOTIONAL_ABUSE    ON ZC_IPV_EMOTIONAL_ABUSE.IPV_EMOTIONAL_ABUSE_C      = s.IPV_EMOTIONAL_ABUSE_C
    LEFT JOIN ZC_IPV_FEAR               ON ZC_IPV_FEAR.IPV_FEAR_C                            = s.IPV_FEAR_C
    LEFT JOIN ZC_IPV_SEXUAL_ABUSE       ON ZC_IPV_SEXUAL_ABUSE.IPV_SEXUAL_ABUSE_C            = s.IPV_SEXUAL_ABUSE_C
    LEFT JOIN ZC_IPV_PHYSICAL_ABUSE     ON ZC_IPV_PHYSICAL_ABUSE.IPV_PHYSICAL_ABUSE_C        = s.IPV_PHYSICAL_ABUSE_C
    LEFT JOIN ZC_ALCOHOL_FREQ           ON ZC_ALCOHOL_FREQ.ALCOHOL_FREQ_C                    = s.ALCOHOL_FREQ_C
    LEFT JOIN ZC_ALCOHOL_DRINKS_PER_DAY ON ZC_ALCOHOL_DRINKS_PER_DAY.ALCOHOL_DRINKS_PER_DAY_C = s.ALCOHOL_DRINKS_PER_DAY_C
    LEFT JOIN ZC_ALCOHOL_BINGE          ON ZC_ALCOHOL_BINGE.ALCOHOL_BINGE_C                  = s.ALCOHOL_BINGE_C
    LEFT JOIN ZC_LIVING_W_SPOUSE        ON ZC_LIVING_W_SPOUSE.LIVING_W_SPOUSE_C              = s.LIVING_W_SPOUSE_C
    LEFT JOIN ZC_DAILY_STRESS           ON ZC_DAILY_STRESS.DAILY_STRESS_C                    = s.DAILY_STRESS_C
    LEFT JOIN ZC_PHONE_COMMUNICATION    ON ZC_PHONE_COMMUNICATION.PHONE_COMMUNICATION_C      = s.PHONE_COMMUNICATION_C
    LEFT JOIN ZC_SOCIALIZATION_FREQ     ON ZC_SOCIALIZATION_FREQ.SOCIALIZATION_FREQ_C        = s.SOCIALIZATION_FREQ_C
    LEFT JOIN ZC_CHURCH_ATTENDANCE      ON ZC_CHURCH_ATTENDANCE.SDOH_CHURCH_ATTENDANCE_C     = s.CHURCH_ATTENDANCE_C
    LEFT JOIN ZC_CLUBMTG_ATTENDANCE     ON ZC_CLUBMTG_ATTENDANCE.CLUBMTG_ATTENDANCE_C        = s.CLUBMTG_ATTENDANCE_C
    LEFT JOIN ZC_CLUB_MEMBER            ON ZC_CLUB_MEMBER.CLUB_MEMBER_C                      = s.CLUB_MEMBER_C
    LEFT JOIN ZC_PHYS_ACT_DAYS_PER_WEEK ON ZC_PHYS_ACT_DAYS_PER_WEEK.PHYS_ACT_DAYS_PER_WEEK_C = s.PHYS_ACT_DAYS_PER_WEEK_C
    LEFT JOIN ZC_PHYS_ACT_MIN_PER_SESS  ON ZC_PHYS_ACT_MIN_PER_SESS.PHYS_ACT_MIN_PER_SESS_C  = s.PHYS_ACT_MIN_PER_SESS_C
    LEFT JOIN ZC_FOOD_INSECURITY_SCARCE ON ZC_FOOD_INSECURITY_SCARCE.FOOD_INSECURITY_SCARCE_C = s.FOOD_INSECURITY_SCARCE_C
    LEFT JOIN ZC_FOOD_INSECURITY_WORRY  ON ZC_FOOD_INSECURITY_WORRY.FOOD_INSECURITY_WORRY_C  = s.FOOD_INSECURITY_WORRY_C
    LEFT JOIN ZC_MED_TRANSPORT_NEEDS    ON ZC_MED_TRANSPORT_NEEDS.MED_TRANSPORT_NEEDS_C      = s.MED_TRANSPORT_NEEDS_C
    LEFT JOIN ZC_OTHER_TRANSPORT_NEEDS  ON ZC_OTHER_TRANSPORT_NEEDS.OTHER_TRANSPORT_NEEDS_C  = s.OTHER_TRANSPORT_NEEDS_C
    -- Document table (for HX_SOCIAL_DOC) - kept to preserve possible row-multiplicity semantics
    LEFT JOIN PAT_SOCIAL_HX_DOC psd ON psd.PAT_ID = s.PAT_ID
    WHERE s.CONTACT_DATE >= p.period_start
      AND s.CONTACT_DATE <  p.period_end
)
SELECT * FROM base_sh;